-- MySQL Script generated by MySQL Workbench
-- Wed May 31 12:07:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stages
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stages
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stages` DEFAULT CHARACTER SET utf8 ;
USE `stages` ;

-- -----------------------------------------------------
-- Table `stages`.`competence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`competence` (
  `idcompetence` INT(10) NOT NULL AUTO_INCREMENT,
  `nomcompetence` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`idcompetence`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`couleur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`couleur` (
  `idcouleur` INT(10) NOT NULL AUTO_INCREMENT,
  `nomcouleur` VARCHAR(100) NOT NULL,
  `codehexa` VARCHAR(6) NOT NULL DEFAULT '000000',
  PRIMARY KEY (`idcouleur`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`type_entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`type_entreprise` (
  `idtypeentreprise` INT(10) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  `idcouleur` INT(10) NOT NULL,
  PRIMARY KEY (`idtypeentreprise`),
  INDEX `idcouleur_idx` (`idcouleur` ASC),
  CONSTRAINT `fkidcouleur`
    FOREIGN KEY (`idcouleur`)
    REFERENCES `stages`.`couleur` (`idcouleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`entreprise` (
  `identreprise` INT(10) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL DEFAULT '',
  `adresse` VARCHAR(100) NOT NULL DEFAULT '',
  `codepostal` VARCHAR(8) NOT NULL DEFAULT '',
  `ville` VARCHAR(100) NOT NULL DEFAULT '',
  `pays` VARCHAR(100) NOT NULL DEFAULT '',
  `email` VARCHAR(256) NOT NULL DEFAULT '""',
  `idtypeentreprise` INT(10) NOT NULL,
  PRIMARY KEY (`identreprise`),
  INDEX `idtypeentreprise_idx` (`idtypeentreprise` ASC),
  CONSTRAINT `fkidtypeentreprise`
    FOREIGN KEY (`idtypeentreprise`)
    REFERENCES `stages`.`type_entreprise` (`idtypeentreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 392
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`contact` (
  `idcontact` INT(10) NOT NULL AUTO_INCREMENT,
  `nomcontact` VARCHAR(100) NOT NULL DEFAULT '',
  `prenomcontact` VARCHAR(100) NOT NULL DEFAULT '',
  `telephone` VARCHAR(20) NOT NULL,
  `telecopie` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `identreprise` INT(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idcontact`),
  INDEX `foreign_key_contact_identreprise` (`identreprise` ASC),
  INDEX `idcontact_idx` (`identreprise` ASC),
  CONSTRAINT `fkidentreprise`
    FOREIGN KEY (`identreprise`)
    REFERENCES `stages`.`entreprise` (`identreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 615
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`etudiant` (
  `idetudiant` INT(10) NOT NULL AUTO_INCREMENT,
  `nometudiant` VARCHAR(100) NOT NULL DEFAULT '',
  `prenometudiant` VARCHAR(100) NOT NULL DEFAULT '',
  `email_institutionnel` VARCHAR(200) NOT NULL DEFAULT '',
  `email_personnel` VARCHAR(200) NULL DEFAULT NULL,
  `codeetudiant` VARCHAR(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`idetudiant`))
ENGINE = InnoDB
AUTO_INCREMENT = 320
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`datesoutenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`datesoutenance` (
  `iddatesoutenance` INT(10) NOT NULL AUTO_INCREMENT,
  `jour` INT(2) NOT NULL DEFAULT '0',
  `mois` INT(2) NOT NULL DEFAULT '0',
  `annee` INT(4) NOT NULL DEFAULT '0',
  `convocation` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iddatesoutenance`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`salle_soutenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`salle_soutenance` (
  `idsalle` INT(10) NOT NULL AUTO_INCREMENT,
  `nomsalle` VARCHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`idsalle`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`soutenances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`soutenances` (
  `idsoutenance` INT(10) NOT NULL AUTO_INCREMENT,
  `heuredebut` INT(2) NOT NULL DEFAULT '0',
  `mindebut` INT(2) NOT NULL DEFAULT '0',
  `ahuitclos` TINYINT(4) NOT NULL DEFAULT '0',
  `iddatesoutenance` INT(10) NOT NULL,
  `idsalle` INT(10) NOT NULL,
  PRIMARY KEY (`idsoutenance`),
  INDEX `foreign_key_soutenances_idsalle` (`idsalle` ASC),
  INDEX `foreign_key_soutenances_iddatesoutenance` (`iddatesoutenance` ASC),
  INDEX `iddatesoutenance_idx` (`iddatesoutenance` ASC),
  INDEX `idsalle_idx` (`idsalle` ASC),
  CONSTRAINT `fkiddatesoutenance`
    FOREIGN KEY (`iddatesoutenance`)
    REFERENCES `stages`.`datesoutenance` (`iddatesoutenance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidsalle`
    FOREIGN KEY (`idsalle`)
    REFERENCES `stages`.`salle_soutenance` (`idsalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 437
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`parrain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`parrain` (
  `idparrain` INT(10) NOT NULL AUTO_INCREMENT,
  `nomparrain` VARCHAR(100) NOT NULL DEFAULT '',
  `prenomparrain` VARCHAR(100) NOT NULL DEFAULT '',
  `emailparrain` VARCHAR(200) NOT NULL DEFAULT '',
  `idcouleur` INT(10) NOT NULL,
  PRIMARY KEY (`idparrain`),
  INDEX `foreign_key_couleur_idcouleur` (`idcouleur` ASC),
  INDEX `idcouleur_idx` (`idcouleur` ASC),
  CONSTRAINT `fkidcouleur`
    FOREIGN KEY (`idcouleur`)
    REFERENCES `stages`.`couleur` (`idcouleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`theme_destage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`theme_destage` (
  `idtheme` INT NOT NULL,
  `theme` VARCHAR(10) NOT NULL,
  `idcouleur` INT(10) NOT NULL,
  PRIMARY KEY (`idtheme`),
  INDEX `idcouleur_idx` (`idcouleur` ASC),
  CONSTRAINT `fkidcouleur`
    FOREIGN KEY (`idcouleur`)
    REFERENCES `stages`.`couleur` (`idcouleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`convention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`convention` (
  `idconvention` INT(10) NOT NULL AUTO_INCREMENT,
  `sujetdestage` MEDIUMTEXT NOT NULL,
  `asonresume` TINYINT(4) NOT NULL DEFAULT '0',
  `note` DECIMAL(4,2) NOT NULL DEFAULT '0.00',
  `idparrain` INT(10) NOT NULL,
  `idexaminateur` INT(10) NOT NULL,
  `idetudiant` INT(10) NOT NULL DEFAULT '0',
  `idsoutenance` INT(10) NOT NULL,
  `idcontact` INT(10) NOT NULL,
  `idtheme` INT(10) NOT NULL,
  PRIMARY KEY (`idconvention`),
  INDEX `foreign_key_convention_idparrain` (`idparrain` ASC),
  INDEX `foreign_key_convention_idetudiant` (`idetudiant` ASC),
  INDEX `foreign_key_convention_idsoutenance` (`idsoutenance` ASC),
  INDEX `foreign_key_convention_idcontact` (`idcontact` ASC),
  INDEX `foreign_key_convention_idexaminateur` (`idexaminateur` ASC),
  INDEX `idetudiant_idx` (`idetudiant` ASC),
  INDEX `idsoutenance_idx` (`idsoutenance` ASC),
  INDEX `idparrain_idx` (`idparrain` ASC),
  INDEX `idexaminateur_idx` (`idexaminateur` ASC),
  INDEX `idcontact_idx` (`idcontact` ASC),
  INDEX `idtheme_idx` (`idtheme` ASC),
  CONSTRAINT `fkidetudiant`
    FOREIGN KEY (`idetudiant`)
    REFERENCES `stages`.`etudiant` (`idetudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidsoutenance`
    FOREIGN KEY (`idsoutenance`)
    REFERENCES `stages`.`soutenances` (`idsoutenance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidparrain`
    FOREIGN KEY (`idparrain`)
    REFERENCES `stages`.`parrain` (`idparrain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidexaminateur`
    FOREIGN KEY (`idexaminateur`)
    REFERENCES `stages`.`parrain` (`idparrain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidcontact`
    FOREIGN KEY (`idcontact`)
    REFERENCES `stages`.`contact` (`idcontact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidtheme`
    FOREIGN KEY (`idtheme`)
    REFERENCES `stages`.`theme_destage` (`idtheme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 387
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`filiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`filiere` (
  `idfiliere` INT(10) NOT NULL AUTO_INCREMENT,
  `nomfiliere` VARCHAR(50) NOT NULL DEFAULT '',
  `temps_soutenance` INT(3) NOT NULL DEFAULT '20',
  `affDepot` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idfiliere`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`fluxrss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`fluxrss` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `link` TEXT CHARACTER SET 'latin1' NOT NULL,
  `timestamp` INT(12) NOT NULL DEFAULT '0',
  `contents` TEXT CHARACTER SET 'latin1' NOT NULL,
  `author` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = MyISAM
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`offredestage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`offredestage` (
  `idoffre` INT(10) NOT NULL AUTO_INCREMENT,
  `sujet` TEXT NOT NULL,
  `titre` VARCHAR(120) NOT NULL DEFAULT '',
  `listeenvironnement` TEXT NOT NULL,
  `dureemin` VARCHAR(50) NOT NULL DEFAULT '',
  `dureemax` VARCHAR(50) NOT NULL DEFAULT '',
  `indemnite` DOUBLE NOT NULL DEFAULT '0',
  `remarques` TEXT NOT NULL,
  `estVisible` TINYINT(4) NOT NULL DEFAULT '0',
  `idcontact` INT(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idoffre`),
  INDEX `foreign_key_offredestage_idcontact` (`idcontact` ASC),
  INDEX `idcontact_idx` (`idcontact` ASC),
  CONSTRAINT `fkidcontact`
    FOREIGN KEY (`idcontact`)
    REFERENCES `stages`.`contact` (`idcontact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 317
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`parcours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`parcours` (
  `idparcours` INT(10) NOT NULL AUTO_INCREMENT,
  `nomparcours` VARCHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`idparcours`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`profilsouhaite_offredestage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`profilsouhaite_offredestage` (
  `idoffre` INT(10) NOT NULL DEFAULT '0',
  `idfiliere` INT(10) NOT NULL DEFAULT '0',
  INDEX `foreign_key_theme_offreDeStage_idfiliere` (`idfiliere` ASC),
  INDEX `foreign_key_theme_offreDeStage_idoffre` (`idoffre` ASC),
  INDEX `idoffre_idx` (`idoffre` ASC),
  INDEX `idfiliere_idx` (`idfiliere` ASC),
  CONSTRAINT `fkidoffre`
    FOREIGN KEY (`idoffre`)
    REFERENCES `stages`.`offredestage` (`idoffre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidfiliere`
    FOREIGN KEY (`idfiliere`)
    REFERENCES `stages`.`filiere` (`idfiliere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`promotion` (
  `idpromotion` INT(10) NOT NULL AUTO_INCREMENT,
  `anneeuniversitaire` INT(10) NOT NULL DEFAULT '0',
  `idparcours` INT(10) NOT NULL,
  `idfiliere` INT(10) NOT NULL,
  `email_promotion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idpromotion`),
  INDEX `foreign_key_promotion_idfiliere` (`idfiliere` ASC),
  INDEX `foreign_key_promotion_idparcours` (`idparcours` ASC),
  INDEX `idfiliere_idx` (`idfiliere` ASC),
  INDEX `idparcours_idx` (`idparcours` ASC),
  CONSTRAINT `fkidfiliere`
    FOREIGN KEY (`idfiliere`)
    REFERENCES `stages`.`filiere` (`idfiliere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidparcours`
    FOREIGN KEY (`idparcours`)
    REFERENCES `stages`.`parcours` (`idparcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`relation_competence_offredestage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`relation_competence_offredestage` (
  `idcompetence` INT(10) NOT NULL DEFAULT '0',
  `idoffre` INT(10) NOT NULL DEFAULT '0',
  INDEX `foreign_key_relation_competence_offreDeStage_idcompetence` (`idcompetence` ASC),
  INDEX `foreign_key_relation_competence_offreDeStage_idoffre` (`idoffre` ASC),
  INDEX `idoffre_idx` (`idoffre` ASC),
  INDEX `idcompetence_idx` (`idcompetence` ASC),
  CONSTRAINT `fkidoffre`
    FOREIGN KEY (`idoffre`)
    REFERENCES `stages`.`offredestage` (`idoffre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidcompetence`
    FOREIGN KEY (`idcompetence`)
    REFERENCES `stages`.`competence` (`idcompetence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`relation_promotion_datesoutenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`relation_promotion_datesoutenance` (
  `iddatesoutenance` INT(10) NOT NULL DEFAULT '0',
  `idpromotion` INT(10) NOT NULL DEFAULT '0',
  INDEX `foreign_key_relation_promotion_dateSoutance_iddatesoutenance` (`iddatesoutenance` ASC),
  INDEX `foreign_key_relation_promotion_dateSoutance_idpromotion` (`idpromotion` ASC),
  INDEX `iddatesoutenance_idx` (`iddatesoutenance` ASC),
  INDEX `idpromotion_idx` (`idpromotion` ASC),
  CONSTRAINT `fkiddatesoutenance`
    FOREIGN KEY (`iddatesoutenance`)
    REFERENCES `stages`.`datesoutenance` (`iddatesoutenance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidpromotion`
    FOREIGN KEY (`idpromotion`)
    REFERENCES `stages`.`promotion` (`idpromotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`relation_promotion_etudiant_convention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`relation_promotion_etudiant_convention` (
  `idconvention` INT(10) NOT NULL DEFAULT '0',
  `idpromotion` INT(10) NOT NULL DEFAULT '0',
  `idetudiant` INT(10) NOT NULL DEFAULT '0',
  INDEX `foreign_key_relation_promotion_etudiant_convention_idetudiant` (`idetudiant` ASC),
  INDEX `foreign_key_relation_promotion_etudiant_convention_idconvention` (`idconvention` ASC),
  INDEX `foreign_key_relation_promotion_etudiant_convention_idpromotion` (`idpromotion` ASC),
  INDEX `idconvention_idx` (`idconvention` ASC),
  INDEX `idpromotion_idx` (`idpromotion` ASC),
  INDEX `idetudiant_idx` (`idetudiant` ASC),
  CONSTRAINT `fkidconvention`
    FOREIGN KEY (`idconvention`)
    REFERENCES `stages`.`convention` (`idconvention`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidpromotion`
    FOREIGN KEY (`idpromotion`)
    REFERENCES `stages`.`promotion` (`idpromotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidetudiant`
    FOREIGN KEY (`idetudiant`)
    REFERENCES `stages`.`etudiant` (`idetudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`sujetdestage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`sujetdestage` (
  `idsujetdestage` INT(10) NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `valide` TINYINT(4) NOT NULL DEFAULT '0',
  `enattente` TINYINT(4) NOT NULL DEFAULT '0',
  `idetudiant` INT(10) NOT NULL DEFAULT '0',
  `idpromotion` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idsujetdestage`),
  INDEX `foreign_key_sujetdestage_idetudiant` (`idetudiant` ASC),
  INDEX `idpromotion_idx` (`idpromotion` ASC),
  INDEX `idetudiant_idx` (`idetudiant` ASC),
  CONSTRAINT `fkidpromotion`
    FOREIGN KEY (`idpromotion`)
    REFERENCES `stages`.`promotion` (`idpromotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidetudiant`
    FOREIGN KEY (`idetudiant`)
    REFERENCES `stages`.`etudiant` (`idetudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 272
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`taches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`taches` (
  `idtache` INT(10) NOT NULL AUTO_INCREMENT,
  `intitule` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `statut` VARCHAR(20) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL DEFAULT 'Pas fait',
  `priorite` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `datelimite` DATE NOT NULL,
  PRIMARY KEY (`idtache`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`theme_offredestage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`theme_offredestage` (
  `idparcours` INT(10) NOT NULL DEFAULT '0',
  `idoffre` INT(10) NOT NULL DEFAULT '0',
  INDEX `foreign_key_profilSouhaite_offreDeStage_idoffre` (`idoffre` ASC),
  INDEX `foreign_key_profilSouhaite_offreDeStage_idparcours` (`idparcours` ASC),
  INDEX `idoffre_idx` (`idoffre` ASC),
  INDEX `idparcours_idx` (`idparcours` ASC),
  CONSTRAINT `fkidoffre`
    FOREIGN KEY (`idoffre`)
    REFERENCES `stages`.`offredestage` (`idoffre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidparcours`
    FOREIGN KEY (`idparcours`)
    REFERENCES `stages`.`parcours` (`idparcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`convocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`convocation` (
  `idconvocation` INT(10) NOT NULL,
  `envoi` TINYINT(4) NOT NULL DEFAULT 0,
  `idsoutenance` INT(10) NOT NULL,
  PRIMARY KEY (`idconvocation`),
  INDEX `idsoutenance_idx` (`idsoutenance` ASC),
  CONSTRAINT `fkidsoutenance`
    FOREIGN KEY (`idsoutenance`)
    REFERENCES `stages`.`soutenances` (`idsoutenance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stages`.`attribution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`attribution` (
  `idattribution` INT(10) NOT NULL,
  `envoi` TINYINT(4) NOT NULL,
  `idconvention` INT(10) NOT NULL,
  PRIMARY KEY (`idattribution`),
  INDEX `idconvention_idx` (`idconvention` ASC),
  CONSTRAINT `fkidconvention`
    FOREIGN KEY (`idconvention`)
    REFERENCES `stages`.`convention` (`idconvention`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
